name: project_maps
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"
dependencies:
  bloc: ^8.1.1
  bloc_provider: ^1.0.0
  cloud_firestore: ^4.4.4
  cloud_firestore_odm: ^1.0.0-dev.51
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.15
  fl_chart: ^0.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_map: ^3.1.0
  flutter_polyline_points: ^1.0.0
  flutter_speed_dial: ^6.2.0
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.2.1
  geocoding: ^2.0.5
  geojson: ^1.0.0
  geolocator: ^9.0.2
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.6+4
  latlong2: ^0.8.1
  location: ^4.3.0
  pushy_flutter: ^2.0.12
  shared_preferences: ^2.0.18
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/duck.jpg
    - assets/
  uses-material-design: true
